### ISSUE TITLE
Request addition of "liquidity/Financial Health" ratios

### ISSUE THREAD

**Issue by linwoodc3** [petercerno/good-morning#1]
Greetings:

This is a great project; I'm wondering if it's possible to add the liquidity/Financial Health ratios from the "Financial Health" tab.  This includes things like the current ratio and debt/equity.  Those are core figures for value investors.  I don't think the current code pulls those.  I'm still trying to get the code working on my machine, but did get some output from the older Python 2.7 version of your code.  Trying Python 3 version now.  But, it would be great to have the current ratio and debt/equity returned in the pandas dataframe as well.  

They are here:  http://financials.morningstar.com/ratios/r.html?t=PFE&region=usa&culture=en-US

**Comment by linwoodc3** [comment]
Disregard; I finally got the Python 3 version to work and ALL of the ratios are there.  This is awesome.  I am mixing this with the value investor stock analysis method to evaluate stocks in an iPython Notebook.

**Comment by petercerno** [comment]
Hi, thanks for comment. I am glad that it works as intended. :) Let me know if there are any other problems.
