### ISSUE TITLE
Install the module

### ISSUE THREAD

**Issue by fakeInsights** [petercerno/good-morning#2]
- I'm so use to using pip, so this may seem like a weird question but, how do I install good_morning so I can import it as described, "import good_morning as gm"
- Is it still working, if not can you recommend another package. 

Thanks in advance.

**Comment by petercerno** [comment]
Hi, you cannot install it by any package manager, you need to download the source code. I am not sure if it is still working (I have not tested it in a while). However, it should be relatively easy to fix any issues. Thanks!

**Comment by fakeInsights** [comment]
thanks for the reply
