### ISSUE TITLE
Pull request to make pypi module

### ISSUE THREAD

**Issue by linwoodc3** [petercerno/good-morning#4]
Checking to see if you're still around.  If not, I have taken your code and made it "pip installable".  Before doing a copy and update of your repo, I'd like to try and do a pull request.  If not, I don't mind taking your code and pushing.  I kept all your licensing and origination info to make sure you get complete credit.  I was just making it so folks could pip install it.  You made a great project.

**Comment by linwoodc3** [comment]
Here is the module; I just changed the name becuase it will be easier for people to find.  https://github.com/linwoodc3/morningstar 

Let me know if I can do a pull request to your repo.  You could add me as a person with permission to handle merges/issues if you don't have time to maintain the repo.  But, I would like to try to keep things going from your original.

**Comment by petercerno** [comment]
Hi, cool, feel free to do a pull request. I will not grant full permissions, but will be able to handle merges. Thanks for keeping it alive.

**Comment by linwoodc3** [comment]
will do
